/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.main;

/**
 *
 * @author RIO
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        initializeSystem();
        setupCardLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
private model.ecosystem.EcoSystem ecoSystem;
    private javax.swing.JPanel userProcessContainer;
    private java.awt.CardLayout cardLayout;


    private void initializeSystem() {
        ecoSystem = model.ecosystem.EcoSystem.getInstance();
        util.faker.DataGenerator.populateEcoSystem(ecoSystem);
        System.out.println("System initialized with fake data!");
        System.out.println("Networks created: " + ecoSystem.getNetworks().size());
    }

    private void setupCardLayout() {
        // Set frame properties
        setTitle("Community Issue Reporting & Resolution Management System");
        setSize(1200, 800);
        setLocationRelativeTo(null);

       userProcessContainer = new javax.swing.JPanel();
cardLayout = new java.awt.CardLayout();
userProcessContainer.setLayout(cardLayout);


        // Clear the default layout and add our container
        getContentPane().removeAll();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(userProcessContainer, java.awt.BorderLayout.CENTER);

        // Add login panel as first screen
        ui.login.LoginJPanel loginPanel = new ui.login.LoginJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add(loginPanel, "LoginPanel");
    }
    public void navigateTo(javax.swing.JPanel panel, String name) {
    userProcessContainer.add(panel, name);
    cardLayout.show(userProcessContainer, name);
}
// STEP 1: ROUTING BASED ON ROLE
// Inside src/ui/main/MainJFrame.java

public void loadDashboard(model.userAccount.UserAccount user) {
    // Clear screen
    userProcessContainer.removeAll();

    // 1. FIND CONTEXT: Determine which Network, Enterprise, and Organization this user belongs to
    model.network.Network inNetwork = null;
    model.enterprise.Enterprise inEnterprise = null;
    model.organization.Organization inOrganization = null;

    // Search the entire ecosystem
    searchLoop:
    for (model.network.Network network : ecoSystem.getNetworks()) {
        for (model.enterprise.Enterprise ent : network.getEnterprises()) {
            for (model.organization.Organization org : ent.getOrganizations()) {
                for (model.userAccount.UserAccount ua : org.getUserAccounts()) {
                    if (ua.getUsername().equals(user.getUsername())) {
                        inNetwork = network;
                        inEnterprise = ent;
                        inOrganization = org;
                        break searchLoop; // Found the user, stop searching
                    }
                }
            }
        }
    }

    // 2. LOAD DASHBOARD: Pass the found Enterprise/Organization to the Role
    // This fixes the "null" issue because we now pass 'inOrganization' and 'inEnterprise'
    javax.swing.JPanel workArea = user.getRole().createWorkArea(
            userProcessContainer,
            user,
            inOrganization, // <--- Was null, now passing correct Org
            inEnterprise,   // <--- Was null, now passing correct Enterprise (Critical for Supervisor)
            ecoSystem
    );

    userProcessContainer.add("WorkArea", workArea);
    java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
}
}