/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import java.awt.CardLayout;

/**
 *
 * @author RIO
 */
public class AdminDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboardJPanel
     */
    private javax.swing.JPanel userProcessContainer;
    private model.ecosystem.EcoSystem ecoSystem;
    private model.userAccount.UserAccount userAccount;
    private String adminType; // "SYSTEM", "NETWORK", "ENTERPRISE", "ORGANIZATION"

    public AdminDashboardJPanel(javax.swing.JPanel userProcessContainer, model.ecosystem.EcoSystem ecoSystem, model.userAccount.UserAccount account, String adminType) {
    this.userProcessContainer = userProcessContainer;
    this.ecoSystem = ecoSystem;
    this.userAccount = account;
    this.adminType = adminType; // "SYSTEM", "NETWORK", "ENTERPRISE", "ORGANIZATION"
    //updated admin login view
    initComponents();
    configureView(); // <--- Call the new method here
}

private void configureView() {
    // 1. Hide all buttons by default
    btnManageNetworks.setVisible(false);
    btnManageEnterprise.setVisible(false);
    btnManageOrganization.setVisible(false);
    btnManageUsers.setVisible(false);

    // 2. Show buttons based on adminType
    if (adminType != null) {
        switch (adminType) {
            case "SYSTEM":
                btnManageNetworks.setVisible(true);
                btnManageEnterprise.setVisible(true);
                btnManageOrganization.setVisible(true);
                btnManageUsers.setVisible(true);
                break;
            case "NETWORK":
                btnManageEnterprise.setVisible(true);
                btnManageOrganization.setVisible(true);
                btnManageUsers.setVisible(true);
                break;
            case "ENTERPRISE":
                btnManageOrganization.setVisible(true);
                btnManageUsers.setVisible(true);
                break;
            case "ORGANIZATION":
                btnManageUsers.setVisible(true);
                break;
        }
    }
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        sidebarPanel = new javax.swing.JPanel();
        btnManageNetworks = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnManageOrganization = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        btnManageNetworks.setText("Manage Networks");
        btnManageNetworks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworksActionPerformed(evt);
            }
        });

        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });

        btnManageOrganization.setText("Manage Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });

        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageNetworks)
                            .addComponent(btnManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(btnManageNetworks)
                .addGap(53, 53, 53)
                .addComponent(btnManageEnterprise)
                .addGap(44, 44, 44)
                .addComponent(btnManageOrganization)
                .addGap(60, 60, 60)
                .addComponent(btnManageUsers)
                .addGap(31, 31, 31)
                .addComponent(btnLogout)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(sidebarPanel);

        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        add(splitPane);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworksActionPerformed

    ManageNetworksJPanel panel = new ManageNetworksJPanel(workArea, ecoSystem);
    workArea.add("ManageNetworkJPanel", panel);
    ((CardLayout) workArea.getLayout()).next(workArea);


    }//GEN-LAST:event_btnManageNetworksActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
   
        ManageEnterpriseJPanel panel = new ManageEnterpriseJPanel(workArea, ecoSystem);
    workArea.add("ManageEnterpriseJPanel", panel);
    ((CardLayout) workArea.getLayout()).next(workArea);

    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
   
        ManageOrganizationsJPanel panel = new ManageOrganizationsJPanel(workArea, ecoSystem);
    workArea.add("ManageOrganizationJPanel", panel);
    ((CardLayout) workArea.getLayout()).next(workArea);

    }//GEN-LAST:event_btnManageOrganizationActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
       ManageUsersJPanel panel = new ManageUsersJPanel(workArea, ecoSystem);
    workArea.add("ManageUsersJPanel", panel);
    ((CardLayout) workArea.getLayout()).next(workArea);

    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // Go back to login screen
        userProcessContainer.removeAll();
        
        ui.login.LoginJPanel loginPanel = new ui.login.LoginJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add(loginPanel, "Login");
        
        java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
        layout.show(userProcessContainer, "Login");
        
        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetworks;
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
