/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import javax.swing.JPanel;
import model.ecosystem.EcoSystem;

/**
 *
 * @author zenishborad
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private JPanel workArea;
    private EcoSystem ecoSystem;
    private javax.swing.table.DefaultTableModel tableModel;
    
    
   public ManageEnterpriseJPanel(JPanel workArea, EcoSystem ecoSystem) {
    this.workArea = workArea;
    this.ecoSystem = ecoSystem;
    initComponents();
    setupTable();
    loadNetworks();
    loadEnterpriseTypes();
    loadEnterprises();
}
   private void setupTable() {
    tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    tableModel.setColumnIdentifiers(new String[]{"Enterprise Name", "Type", "Network", "Organizations"});
    jTable1.setRowHeight(25);
    jTable1.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
}

private void loadNetworks() {
    cmbNetwork.removeAllItems();
    try {
        for (model.network.Network network : ecoSystem.getNetworks()) {
            cmbNetwork.addItem(network.getName());
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void loadEnterpriseTypes() {
    cmbEnterpriseType.removeAllItems();
    for (model.enterprise.Enterprise.EnterpriseType type : model.enterprise.Enterprise.EnterpriseType.values()) {
        cmbEnterpriseType.addItem(type.getValue());
    }
}

private void loadEnterprises() {
    tableModel.setRowCount(0);
    try {
        for (model.network.Network network : ecoSystem.getNetworks()) {
            for (model.enterprise.Enterprise enterprise : network.getEnterprises()) {
                Object[] row = {
                    enterprise.getName(),
                    enterprise.getEnterpriseType().getValue(),
                    network.getName(),
                    enterprise.getOrganizations().size()
                };
                tableModel.addRow(row);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        lblNetwork = new javax.swing.JLabel();
        cmbNetwork = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        cmbEnterpriseType = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        scrollPane1.add(jScrollPane1);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblNetwork.setText("Network ");

        lblName.setText("Name");

        lblEnterpriseType.setText("Enterprise type");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Manage Enterprise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNetwork)
                                    .addComponent(lblName)
                                    .addComponent(lblEnterpriseType))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(cmbEnterpriseType, 0, 209, Short.MAX_VALUE)
                                    .addComponent(cmbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreate)
                                .addGap(138, 138, 138)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(btnBack)
                                .addGap(59, 59, 59)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseType)
                    .addComponent(cmbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnDelete)
                    .addComponent(btnBack))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String enterpriseName = txtName.getText().trim();
    
    if (enterpriseName.isEmpty() || enterpriseName.length() < 3) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Enterprise name must be 3+ characters!", 
            "Validation Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        String selectedNetworkName = (String) cmbNetwork.getSelectedItem();
        String selectedEnterpriseTypeName = (String) cmbEnterpriseType.getSelectedItem();
        
        // Find the selected network
        model.network.Network selectedNetwork = null;
        for (model.network.Network network : ecoSystem.getNetworks()) {
            if (network.getName().equals(selectedNetworkName)) {
                selectedNetwork = network;
                break;
            }
        }
        
        if (selectedNetwork == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Network not found!", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Find the enterprise type enum
        model.enterprise.Enterprise.EnterpriseType enterpriseType = null;
        for (model.enterprise.Enterprise.EnterpriseType type : model.enterprise.Enterprise.EnterpriseType.values()) {
            if (type.getValue().equals(selectedEnterpriseTypeName)) {
                enterpriseType = type;
                break;
            }
        }
        
        // Create the enterprise
        selectedNetwork.createAndAddEnterprise(enterpriseName, enterpriseType);
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Enterprise created successfully: " + enterpriseName, 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Clear form and reload table
        txtName.setText("");
        loadEnterprises();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error creating enterprise: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } 

// TODO add your handling code here:
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please select an enterprise to delete!", 
            "No Selection", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String enterpriseName = (String) tableModel.getValueAt(selectedRow, 0);
    int orgCount = Integer.parseInt(tableModel.getValueAt(selectedRow, 3).toString());
    
    // Check if enterprise has organizations
    if (orgCount > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Cannot delete! Enterprise has " + orgCount + " organizations.\nDelete organizations first.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete enterprise: " + enterpriseName + "?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            boolean deleted = false;
            
            outerLoop:
            for (model.network.Network network : ecoSystem.getNetworks()) {
                model.enterprise.Enterprise toDelete = null;
                for (model.enterprise.Enterprise enterprise : network.getEnterprises()) {
                    if (enterprise.getName().equals(enterpriseName)) {
                        toDelete = enterprise;
                        break;
                    }
                }
                if (toDelete != null) {
                    network.getEnterprises().remove(toDelete);
                    deleted = true;
                    break outerLoop;
                }
            }
            
            if (deleted) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Enterprise deleted successfully!", 
                    "Success", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                loadEnterprises();
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error deleting enterprise: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
 workArea.remove(this);
    java.awt.CardLayout layout = (java.awt.CardLayout) workArea.getLayout();
    layout.previous(workArea);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cmbEnterpriseType;
    private javax.swing.JComboBox<String> cmbNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
