/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.supervisor;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ecosystem.EcoSystem;
import model.enterprise.Enterprise;
import model.organization.Organization;
import model.userAccount.UserAccount;
import model.workQueue.WorkRequest;
import util.enums.Status;
import javax.swing.Timer;
/**
 *
 * @author RIO
 */
public class SupervisorDashboardJPanel extends javax.swing.JPanel {
   
private javax.swing.table.DefaultTableModel tableModel;
    /**
     * Creates new form SupervisorDashboardJPanel
     */
   private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private Enterprise enterprise; // Changed from Organization to Enterprise
    private Timer notificationTimer;

    public SupervisorDashboardJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, UserAccount account, Enterprise enterprise) {
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = account;
        this.enterprise = enterprise;
        
        initComponents();
        setupTable();
        loadWorkers();
        loadUnassignedRequests();
        updateInboxBadge();
        notificationTimer = new Timer(3000, e -> updateInboxBadge());
        notificationTimer.start();
    }
    
    
    private void setupTable() {
        tableModel = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
    }

private void loadWorkers() {
        cmbWorkers.removeAllItems();
        
        if (enterprise == null) return;

        for (Organization org : enterprise.getOrganizations()) {
            for (UserAccount ua : org.getUserAccounts()) {
                // Don't show the Supervisor himself, and don't show Admins
                if (!ua.getRole().getRoleType().isAdmin() && 
                    ua.getRole().getRoleType() != util.enums.RoleType.PUBLIC_WORKS_SUPERVISOR) {
                    
                    // Format: "Worker Name (Role) - Organization"
                    String label = ua.getPerson().getFullName() + " (" + ua.getRole().toString() + ") - " + org.getName();
                    cmbWorkers.addItem(label);
                }
            }
        }
    }

    // FIX 2: Load requests from ALL Organizations
    private void loadUnassignedRequests() {
        tableModel.setRowCount(0);
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("MM/dd/yyyy");

        if (enterprise == null) return;

        for (Organization org : enterprise.getOrganizations()) {
            for (WorkRequest request : org.getWorkQueue().getWorkRequests()) {
                
                // Show requests that are NEW or have no receiver
                if (request.getStatus() == Status.NEW || request.getReceiver() == null) {
                    Object[] row = {
                        request.getRequestId(),
                        request.getIssueType().getValue(),
                        request.getPriority().getValue(),
                        request.getLocation().getStreet(),
                        dateFormat.format(request.getRequestDate())
                    };
                    tableModel.addRow(row);
                }
            }
        }
    }
    
public void updateInboxBadge() {
    try {
        int unreadCount = business.notification.NotificationService.getUnreadCount(userAccount); // Note: Use 'userAccount' or 'account' depending on the variable name in that file
        
        if (unreadCount > 0) {
            btnInbox.setText("Inbox (" + unreadCount + ")");
            btnInbox.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12)); // Make it bold
            btnInbox.setForeground(java.awt.Color.RED); // Make it pop
        } else {
            btnInbox.setText("Inbox");
            btnInbox.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
            btnInbox.setForeground(java.awt.Color.BLACK);
        }
    } catch (Exception e) {
        System.out.println("Error updating badge: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        lblSelectWorker = new javax.swing.JLabel();
        cmbWorkers = new javax.swing.JComboBox<>();
        btnLogout = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scrollPaneRequests = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInbox = new javax.swing.JButton();

        splitPane.setDividerLocation(400);
        splitPane.setLeftComponent(jLabel2);
        splitPane.setRightComponent(jLabel3);

        rightPanel.setPreferredSize(new java.awt.Dimension(400, 251));

        lblSelectWorker.setText("Select Worker to Assign:");

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign to Worker");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Supervisor Dashboard - Assign Work Requests");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Issue Type", "Priority", "Location", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneRequests.setViewportView(jTable1);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scrollPaneRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(lblSelectWorker)
                        .addGap(42, 42, 42)
                        .addComponent(cmbWorkers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addGap(16, 16, 16))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectWorker)
                    .addComponent(cmbWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssign)
                    .addComponent(btnLogout)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(scrollPaneRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnInbox.setText("Inbox");
        btnInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(btnInbox)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        if (notificationTimer != null) {
        notificationTimer.stop();
    }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Go back to login screen
            userProcessContainer.removeAll();

            ui.login.LoginJPanel loginPanel = new ui.login.LoginJPanel(userProcessContainer, ecoSystem);
            userProcessContainer.add(loginPanel, "Login");

            java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
            layout.show(userProcessContainer, "Login");

            userProcessContainer.revalidate();
            userProcessContainer.repaint();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadUnassignedRequests();
        loadWorkers();
        updateInboxBadge();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Data refreshed!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a request!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cmbWorkers.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a worker!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String requestId = (String) tableModel.getValueAt(selectedRow, 0);

            // 1. Find the Request (Search all orgs)
            WorkRequest request = null;
            Organization requestOrg = null;

            outerLoop:
            for (Organization org : enterprise.getOrganizations()) {
                for (WorkRequest req : org.getWorkQueue().getWorkRequests()) {
                    if (req.getRequestId().equals(requestId)) {
                        request = req;
                        requestOrg = org;
                        break outerLoop;
                    }
                }
            }

            if (request == null) return;

            // 2. Find the Worker (Parse from Dropdown)
            String selection = (String) cmbWorkers.getSelectedItem();
            // Selection format: "Name (Role) - OrgName"
            // We need to match Name and Role carefully, or just search by Name if unique
            // Let's search by Full Name match
            String workerName = selection.substring(0, selection.indexOf(" ("));

            UserAccount selectedWorker = null;

            workerLoop:
            for (Organization org : enterprise.getOrganizations()) {
                for (UserAccount ua : org.getUserAccounts()) {
                    if (ua.getPerson().getFullName().equals(workerName)) {
                        selectedWorker = ua;
                        break workerLoop;
                    }
                }
            }

            if (selectedWorker != null) {
                // 3. Assign
                request.setReceiver(selectedWorker);
                request.setStatus(Status.ASSIGNED);
                selectedWorker.getWorkQueue().addWorkRequest(request);

                business.notification.NotificationService.notifyNewAssignment(selectedWorker, request);

                JOptionPane.showMessageDialog(this,
                    "Assigned Request " + requestId + " to " + selectedWorker.getUsername());

                loadUnassignedRequests(); // Refresh table
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error assigning: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
        // TODO add your handling code here:
        ui.common.ViewNotificationsJPanel inboxPanel = new ui.common.ViewNotificationsJPanel(userProcessContainer, userAccount);
    userProcessContainer.add("Inbox", inboxPanel);
    java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnInbox;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbWorkers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSelectWorker;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JScrollPane scrollPaneRequests;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables


}
