/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.common;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.userAccount.UserAccount;
import business.notification.NotificationService;
import business.notification.NotificationService.Notification;
import java.text.SimpleDateFormat;
import java.awt.CardLayout;
/**
 *
 * @author deep2
 */
public class ViewNotificationsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    /**
     * Creates new form ViewNotificationsJPanel
     */
    public ViewNotificationsJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents(); // Keep the auto-generated call
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        
        setupTable();
        populateNotifications();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotifications = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("My Notifications");

        tblNotifications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Time", "Type", "Message", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblNotifications);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblNotifications;
    // End of variables declaration//GEN-END:variables
private void setupTable() {
        DefaultTableModel model = (DefaultTableModel) tblNotifications.getModel();
        model.setColumnIdentifiers(new Object[]{"Time", "Type", "Message", "Status"});
        tblNotifications.setRowHeight(25);
        tblNotifications.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
    }
private void populateNotifications() {
        DefaultTableModel model = (DefaultTableModel) tblNotifications.getModel();
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd HH:mm");

        // Fetch from the static Service
        for (Notification n : NotificationService.getUserNotifications(account)) {
            Object[] row = {
                sdf.format(n.getTimestamp()),
                n.getType().getValue(),
                n.getMessage(),
                n.isRead() ? "Read" : "Unread"
            };
            model.addRow(row);
            
            // Mark as read immediately upon viewing (or you can add a 'Mark Read' button)
            n.markAsRead();
        }
}
}
